cs394-w20/find-a-time

- database.rules.json
- src/App.js
- src/Db/UpdateDb.js
- src/calendar/AddEvents.js
- src/calendar/ScheduleEvents.js
- Renamed ScheduleEvents -> AddEvents to match the default function it is exporting
- Removed infinite loop from ScheduleEvents (or AddEvents) changed the format of output
- Adjusted UpdateDb to take in the new input from ScheduleEvents
***Problems?***
- Does not take into account changes to a calendar. So if a user logs in the app will automatically update firebase with times the user is busy and implicitly the times the user free. If the user changes a previous time that was busy to free in his/her calendar and then goes to the app, then this change will not be reflected. The busy time will still be busy...... Easy fix with UpdateDb will open issue on Trello
> Changed ScheduleEvents to not infinite loop, changed UpdateDb to take new input from ScheduleEvents

- src/components/Db/GetStartEndTimeForRoomId.js
- src/components/Db/index.js
- src/components/Events/ListUpcomingEvents.js
- src/components/UserProfile/UserProfile.js
- created a new async function to handle this Db request, wrapped some stuff w/  a .then, and refactored a bit
So start/end time no longer static and it now depends on data in firebase
> Get start/end time_interval for roomId = ROOM_ID by querying firebase

- src/calendar/Calendar.js
- src/components/Db/AddUserToRoom.js
- src/components/Db/UpdateDb.js
- src/components/Db/index.js
- changed suzy's code a bit to handle live updating - `Calendar.js` 
- mostly refactoring
> Live Updating works w/ Calendar

- src/App.js
- src/Routes.js
- src/components/NavBar/NavBar.css
- src/components/NavBar/NavBar.js
- src/context/UserContext/UserContext.js
- src/views/Create/Create.js
- src/views/Create/index.js
- src/views/index.js
**Issue**: https://github.com/cs394-w20/find-a-time/issues/17
> add global user context, add create route, handle signouts

- package.json
- src/calendar/Calendar.js
- src/components/EventInvites/EventInvites.css
- src/components/EventInvites/EventInvites.js
- src/components/EventInvites/index.js
- Added static UI page s.t when you click an event a popup shows up asking you whether you want to schedule the event or not. 
- Needs a little bit more work but good enough so i can move on to functionality. Next step make sure there are firebase calls to save data the google gcal event api needs to send events, and then gcal event api calls
> 17 event invites

- src/App.css
- src/App.js
- src/ProtectedRoute.js
- src/Routes.js
- src/components/AuthButton/AuthButton.js
- src/components/Button/Button.css
- src/components/Button/Button.js
- src/components/NavBar/NavBar.js
- src/context/UserContext/UserContext.js
- src/index.css
- src/views/EventPage/EventPage.js
**Issue**: https://github.com/cs394-w20/find-a-time/issues/24
> add loading to button, protected routes, and try catch block on user request

- src/components/Events/ListUpcomingEvents.js
- src/context/UserContext/UserContext.js
- Fixed error in `ListUpcomingEvents` where the data pull was not getting events from the time interval because of a type
- Added `ListUpcomingEvents' to `userContext` -- b4 no event data was being pulled since `ListUpcomingEvents' was called in `UserProfile' and this is now defunct
> Fixed a couple errors

- src/components/Db/AddUserToRoom.js
- src/components/Utility/firebaseEmailToNormalEmail.js
- src/components/Utility/index.js
- src/components/Utility/normalEmailToFirebaseEmail.js
- src/views/EventPage/EventPage.js
- Adds email address and picture to the roomId by using the function `Db.AddUserToRoom.js`
- firebase can't store strings that contain "." so we can't store a email as a key as it is.
- Created a new componenent folder `Utility` all utility functions should be put here
- Added two utitlity functions `firebaseEmailToNormalEmail` and `normalEmailToFirebaseEmail`. The latter replaces "." with "_" in a email, and the former does the reverse.
> Implemented AddUserToRoom once the EventPage is loaded

- package.json
- src/calendar/Calendar.js
- src/components/EventInvites/EventInvites.js
- src/components/EventInvites/_SendEventInvites.js
- src/context/UserContext/UserContext.js
- src/index.html
-Create a gmail account to test event invite email:find.a.time1@gmail.com password:thirtythree333333***
- Calendar.js passes in mostly static data, but `EventInvite` works dynamically everything is turned on. When Calendar is fixed the input will hold additional items: list of emails, a title, and a description. See line 235 in Calendar.js to see invocation of `EventInvite`. The list of emails is hardcoded to just contain find.a.time1@gmail.com .
- **ToDo (issue):** Calendar.js needs to call a firebase function on mount to get the title and description, this function needs to be real time so needs db.on(); this is because the owner can change title or description at any time.
- **ToDo (issue):** Calendar.js should be change to keep track of the email address that are attached to a …
> Finished EventInvite

- src/components/Db/UpdateDb.js
- src/context/UserContext/UserContext.js
- src/views/EventPage/EventPage.js
Change so that ListCalendarEvents is called when opening an event page, change database entry from 1 to "AUTO" when the user is marked busy bc of a Gcal event.
> forgive branch misnomer

- src/components/Events/AddManualEvents.js
- src/views/EventPage/EventPage.js
> switched the busy list to contain emails instead of names

- src/components/Db/UpdateDb.js
Don't merge until fix the names issue. For some reason its not using email but names. Probably can just cut the code i made and merge w/ existing.
> added transaction to ignore MANUAL data when deleting

- package-lock.json
- package.json
- src/ProtectedRoute.js
- src/Routes.js
- src/components/Event/Event.js
- src/components/NavBar/NavBar.scss
- src/views/Create/Create.js
- src/views/Create/GroupDialog.js
- src/views/Create/create.scss
- src/views/EventPage/EventPage.js
- src/views/Login/Login.js
> [create event] Implement the create event functionality

- src/components/Db/AddUserToRoom.js
> Change `AddUserToRoom` to add the user's information to the global user table

- src/components/EventInvites/EventInvites.js
- src/components/EventInvites/EventInvites.scss
- src/views/YourEvents/YourEvents.js
- src/views/YourEvents/YourEvents.scss
- src/views/YourEvents/components/CondensedEvent.js
- src/views/YourEvents/components/CondensedEvent.scss
- src/views/YourEvents/components/UserChips.js
- src/views/YourEvents/components/UserChips.scss
closes #74 
Fixed mobile styling issues for [YourEvent] and [EventInvites]
- add sticky elements to [YourEvent] on the dates on the left hand side, trying to get it exactly like google calendar but I struck out. Have to reorganize code a bit to do that... leave this for another day
- found the error in [EventInvites] btw... its because im using ThemeProvider to do the coloring.. remove ThemeProvider and everything is cool. But then I would have to manually input all the colors w/ css.... again reorganization that would take too long ... leave this for another day
74_tweaksUI (#80)
- [EventInvites] still needs serious cleaning up... maybe i'll do it next week or something but for now its good i guess
> 74 tweaks ui

- src/components/Db/AddUserToRoom.js
- src/components/Db/hasRoom.js
- src/components/Db/index.js
- src/views/EventPage/EventPage.js
closes #87 
- [AddUserToRoom] is now a transaction it checks if room exists b4 doing anything
- new function in Db folder [hasRoom] checks if rooms exists in Db and returns a boolean
- I added a state boolean variable to [EventPage] called dbHasRoom everything waits until this is set to true. However, things are still broken@!!!! I tried going to a room thaat exists and the code pull all my event data back from when i first created my google account. I've been debuggin and its because [GetStartEndTimeForRoomId] which is called in [ListUpcomingEvents] get a null variable instead of the id. On the [EventPage] the id may not be getting passed in or something else funny is happening but [GetStartEndTimeForRoomId] does not get data and the roomId is null i know that
> EventPage won't execute if room is not in Db

- package.json
- src/components/GetRoomsByUser/GetRoomsByUser.js
- src/views/YourEvents/YourEvents.js
- src/views/YourEvents/YourEvents.scss
- src/views/YourEvents/components/CondensedEvent.js
- src/views/YourEvents/components/UserChips.js
- src/views/YourEvents/components/Utility.js
- src/views/YourEvents/components/useScroll.js
closes #81 
- useScroll implements a watcher on the scroll box, anytime a user scrolls it compares the position of all the cards in the scroll box, and with the card with position closest to the top of the scroll box it gets the date converts it to month, and returns the month. Then YourEvents displays this month, s.t now the month changes as the card moves.
- [ReactSearchBox] throws errors, not the best searchbox to use but will do for now. MaterialUi should be used in the future for this
> [YourEvents] month changes while scrolling & searching

- src/components/Db/AddUserToRoom.js
- src/components/Db/hasRoom.js
- src/components/Db/index.js
- src/components/calendar/Calendar.js
- src/components/calendar/GroupCalendar.js
- src/components/calendar/PersonalCalendar.js
- src/views/EventPage/EventPage.js
tried to reincorporate Jide's changes
> 95 fixmergeoverridenew

- src/components/Db/AddUserToRoom.js
- src/components/Popover/popover.scss
- src/views/Create/Create.js
- src/views/YourEvents/YourEvents.js
- src/views/YourEvents/components/CondensedEvent.scss
- src/views/YourEvents/components/UserChips.scss
- src/views/YourEvents/components/useScroll.js
- add a line in [Create] to populate roomId. Tried using the API, but the API needed to be more general in this case for it to work. Instead used a existing function in [Db] to perform this operation
- [popover.scss] adjusted z-index of a element, changed z-index in some of the YourEvents files as well.
- removed a console log from YourEvents.components.useScroll
> Create event now populates /users/{email}/active_rooms/{roomId}

- src/components/calendar/Calendar.js
> 102 disableinvitesforpersonalcal

- src/components/calendar/Calendar.js
- src/utilities.js
depends on pull 105
Removes the add event prompt from the personal calendar, that way you can just drag/click to add a manual event. makes it simpler
> 106 easieraddmanual

- package.json
- src/components/calendar/Calendar.js
- src/components/calendar/CalendarStyles.css
- src/components/calendar/MonthDayNavigator.js
- src/components/calendar/MonthDayNavigator.scss
- src/views/Create/Create.js
- src/views/YourEvents/components/CondensedEvent.scss
- imported a new package 'react-calendar', use calendar to navigate the 4day interval to show.
- overrode a couple styles to make it mobile friendly.
closes #78
> Added a Calendar s.t days switch as dates change

- src/components/Db/ManualEvents.js
- src/components/Db/index.js
- src/components/Events/AddManualEvents.js
- src/components/calendar/Calendar.js
allows users to delete their manually added in events, however must select each slot one by one
> 108 removeownevents

- src/components/EventInvites/EventInvites.js
- src/components/calendar/Calendar.js
> Calendar invites now sent to every user in room w/ correct info

- src/components/EventInvites/EventInvites.js
- src/components/calendar/Calendar.js
You can hover over each event to see which users can attend that time slot:
I'll add more styling to this later on so it looks a bit prettier
> Show detailed info of availability on click!

- src/components/Db/UpdateDb.js
- src/views/Create/Create.js
limited what is stored in db to events in the hour intervals
added hour intervals specified in the create event page to the db entry for event
fixed the automatic entries in db created by create event page (do not create a slot for the end time, if the end time is at 2 the last spot is at 1:30 (which is really 1:30 to 2)
> 112 hourintervals
